### ISSUE TITLE
Spot.java code review

### ISSUE THREAD

**Issue by PaeP3nguin** [VhatAmI/OmniChess#1]
[Line 16](https://github.com/VhatAmI/OmniChess/blob/4e82bc760ecb67d19210ee1b9474dba746b788f1/Spot.java#L16) - piece should be null to start with, right?

[Line 22-24](https://github.com/VhatAmI/OmniChess/blob/4e82bc760ecb67d19210ee1b9474dba746b788f1/Spot.java#L22-24) - can be simplified to " return piece == null; "

Would "square" or "space" make more sense if it's chess?

**Comment by VhatAmI** [comment]
Yes, spots will initialize empty. 

Re-factored isOccupied as suggested.
